version: '3'

tasks:
  up:
    desc: Start all services via Docker Compose (DB + App)
    cmds:
      - docker compose up

  down:
    desc: Stop and remove all containers
    cmds:
      - docker compose down -v

  restart-db:
    desc: Restart the database service
    cmds:
      - docker compose restart db

  logs-db:
    desc: View PostgreSQL logs
    cmds:
      - docker compose logs -f db

  run:
    desc: Run Go app locally (outside Docker)
    cmds:
      - go run cmd/main.go

  run-user-service:
    desc: Run user service
    cmds:
      - ./scripts/run-user-service-test-env.sh {{.MODE}}
    vars:
      MODE: '{{.MODE | default "watch"}}'
  test:
    desc: Run integration tests
    cmds:
      - go test -v ./test/...

  swagger:
    desc: Run Go app locally (outside Docker)
    cmds:
      - swag init --generalInfo cmd/main.go

  regenerate-schema:
    desc: Generate flattened schema.sql
    cmds:
      - docker compose run --rm flyway
      - |
        pg_dump --schema-only --no-owner --no-privileges \
        --dbname=postgresql://localhost:5432/storage_service?user=storage_service \
        | sed '/^-- Dumped by pg_dump/d' \
        > migrations/schema.sql
